version: '3'
services:
  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=energy
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
       - ./influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:8.2.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-config:/etc/grafana/provisioning
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    restart: unless-stopped
networks:
  octograph:
volumes:
  influxdb:
  grafana-storage:
